def choose_gem(month)
  if month=="January"
    gem="Garnet"
    elsif month=="February"
    gem="Amethyst"
    elsif month=="March"
    gem="Aquamarine"
    elsif month=="April"
    gem="Diamond"
    elsif month=="May"
    gem="Emerald"
    elsif month=="June"
    gem="Pearl"
    elsif month=="July"
    gem="Ruby"
    elsif month=="August"
    gem="Peridot"
    elsif month=="September"
    gem="Sapphire"
    elsif month=="October"
    gem="Opal"
    elsif month=="November"
    gem="Topaz"
    elsif month=="December"
    gem="Turquoise"
    elsif month=="january"
    gem="Garnet"
    elsif month=="february"
    gem="Amethyst"
    elsif month=="march"
    gem="Aquamarine"
    elsif month=="april"
    gem="Diamond"
    elsif month=="may"
    gem="Emerald"
    elsif month=="june"
    gem="Pearl"
    elsif month=="july"
    gem="Ruby"
    elsif month=="august"
    gem="Peridot"
    elsif month=="september"
    gem="Sapphire"
    elsif month=="october"
    gem="Opal"
    elsif month=="november"
    gem="Topaz"
    elsif month=="december"
    gem="Turquoise"
  #complete the rest of the method here!
  end

  return gem 
end

